# Generated by Django 5.2.3 on 2025-06-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('character_class', models.CharField(choices=[('guerrier', 'Guerrier'), ('mage', 'Mage'), ('assassin', 'Assassin'), ('archer', 'Archer'), ('paladin', 'Paladin')], max_length=20, verbose_name='Classe')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Personnage',
                'verbose_name_plural': 'Personnages',
                'ordering': ['order', 'name'],
            },
        ),
    ]
