# Generated by Django 5.2.3 on 2025-06-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Description complète affichée sur la page du personnage', verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(help_text='Description affichée sur les cartes (max 500 caractères)', max_length=500, verbose_name='Description courte'),
        ),
    ]
