# Generated by Django 5.2.3 on 2025-08-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('Rushdown', 'Rushdown'), ('Duo Character', 'Duo Character'), ('Set up', 'Set up')], max_length=20, verbose_name='Classe'),
        ),
    ]
