# Generated by Django 5.2.3 on 2025-08-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_character_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='description',
        ),
    ]
